server:
  port: 8189
  servlet:
    context-path: /webapp
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/cloud
    username: postgres
    password: postgrespass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect